In [37]:
import matplotlib as plt
import pandas as pd
import numpy as np

In [38]:
df=pd.read_csv('SHARADAR_SF3A_e25b0a5f97511022da11f3ac8a1b2034.csv')
df=df[(df.shrholders!=0)&(df.shrvalue!=0)&(df.shrunits!=0)]
df.head()

,calendardate,ticker,name,shrholders,cllholders,putholders,wntholders,dbtholders,prfholders,fndholders,...,shrvalue,cllvalue,putvalue,wntvalue,dbtvalue,prfvalue,fndvalue,undvalue,totalvalue,percentoftotal
0,2018-09-30,AAPL,APPLE INC,1685,31,30,0,0,0,0,...,266885854613,4010151374,4200035516,0,0,0,0,0,275096041503,2.436
1,2018-09-30,MSFT,MICROSOFT CORP,1637,21,16,0,2,0,0,...,251773437344,497789239,1141190109,0,283000,0,0,0,253412699692,2.244
2,2018-09-30,AMZN,AMAZON COM INC,1378,25,26,0,2,0,0,...,219079251563,5894684300,8560089000,0,219000,0,0,0,233534243863,2.068
3,2018-09-30,GOOGL,ALPHABET INC,1503,20,18,0,0,0,0,...,226911707903,863637873,2755846289,0,0,0,0,0,230531192065,2.042
5,2018-09-30,FB,FACEBOOK INC,1235,34,22,0,0,0,0,...,108817241141,2139803906,2121244942,0,0,0,0,0,113078289989,1.001

In [39]:
#callput ratio
cpratio=[]
ratio=0
for index, row in df.iterrows():
    if(row['cllunits']==0):
        ratio=0
    else:
        ratio=row['putunits']/row['cllunits']
    cpratio.append(ratio)

In [40]:
#debt-equity ratio
deratio=[]
ratio=0
for index, row in df.iterrows():
    ratio=row['dbtvalue']/row['shrvalue']
    deratio.append(ratio)

In [41]:
#percent preferred
preferred=[]
per=0
for index, row in df.iterrows():
    per=row['prfunits']/(row['shrunits']+row['prfunits'])
    preferred.append(per)

In [42]:
#percent warrants
warrants=[]
per=0
for index, row in df.iterrows():
    per=row['wntunits']/(row['shrunits']+row['prfunits']+row['wntunits'])
    warrants.append(per)

In [44]:
df2=df.assign(callPutRatio=cpratio).assign(debtEquityRatio=deratio).assign(percentPreferred=preferred).assign(percentWarrants=warrants)
df2.head()

,calendardate,ticker,name,shrholders,cllholders,putholders,wntholders,dbtholders,prfholders,fndholders,...,dbtvalue,prfvalue,fndvalue,undvalue,totalvalue,percentoftotal,callPutRatio,debtEquityRatio,percentPreferred,percentWarrants
0,2018-09-30,AAPL,APPLE INC,1685,31,30,0,0,0,0,...,0,0,0,0,275096041503,2.436,1.142899,0.000000e+00,0.0,0.0
1,2018-09-30,MSFT,MICROSOFT CORP,1637,21,16,0,2,0,0,...,283000,0,0,0,253412699692,2.244,1.375652,1.124026e-06,0.0,0.0
2,2018-09-30,AMZN,AMAZON COM INC,1378,25,26,0,2,0,0,...,219000,0,0,0,233534243863,2.068,3.140306,9.996383e-07,0.0,0.0
3,2018-09-30,GOOGL,ALPHABET INC,1503,20,18,0,0,0,0,...,0,0,0,0,230531192065,2.042,1.820644,0.000000e+00,0.0,0.0
5,2018-09-30,FB,FACEBOOK INC,1235,34,22,0,0,0,0,...,0,0,0,0,113078289989,1.001,1.024187,0.000000e+00,0.0,0.0

In [47]:
df2.to_csv("sharadar_new.csv")