In [1]:
import matplotlib as plt
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('SHARADAR_SF3A_e25b0a5f97511022da11f3ac8a1b2034.csv')
df.head()

,calendardate,ticker,name,shrholders,cllholders,putholders,wntholders,dbtholders,prfholders,fndholders,...,shrvalue,cllvalue,putvalue,wntvalue,dbtvalue,prfvalue,fndvalue,undvalue,totalvalue,percentoftotal
0,2018-09-30,AAPL,APPLE INC,1685,31,30,0,0,0,0,...,266885854613,4010151374,4200035516,0,0,0,0,0,275096041503,2.436
1,2018-09-30,MSFT,MICROSOFT CORP,1637,21,16,0,2,0,0,...,251773437344,497789239,1141190109,0,283000,0,0,0,253412699692,2.244
2,2018-09-30,AMZN,AMAZON COM INC,1378,25,26,0,2,0,0,...,219079251563,5894684300,8560089000,0,219000,0,0,0,233534243863,2.068
3,2018-09-30,GOOGL,ALPHABET INC,1503,20,18,0,0,0,0,...,226911707903,863637873,2755846289,0,0,0,0,0,230531192065,2.042
4,2018-09-30,SPY,SPDR S&P 500 ETF TR,0,36,68,0,0,0,1133,...,0,25770862904,40226727136,0,0,0,79956539292,0,145954129332,1.293

In [ ]:
#callput ratio
cpratios=[]
ratio=0
for index, row in df.iterrows():
    if(row['cllunits']==0):
        ratios.append(0)
    else:
        ratio=row['putunits']/row['cllunits']
    ratios.append(ratio)